# Generated by Django 5.2.4 on 2025-08-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_agentfeedback_agent_alter_agentfeedback_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agent',
            name='sample_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
